### PR TITLE
[MCHECKSTYLE-364] - The wiki on codehaus is no more

### PR DESCRIPTION
**Pull request by elharo**
fixes MCHECKSTYLE-364

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [X ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MCHECKSTYLE) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ X] Each commit in the pull request should have a meaningful subject line and body.
 - [X ] Format the pull request title like `[MCHECKSTYLE-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MCHECKSTYLE-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

 - [ X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ X] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by slachiewicz** [comment]
Can be closed - was merged with 7aaf8edbd8dea5e750fcc6bf731f40bcdc736823

**Comment by eolivelli** [comment]
@slachiewicz I am sorry.
As it this was a trivial patch I merged it using the "Merge button" on GitHub.
The result is an empty commit

**Comment by michael-o** [comment]
I have this stupid button because it procudes pointless merge commits. Please don't use it. Explicitly chose rebase and commit, never merge commit.

**Comment by jira-importer** [comment]
Resolve #276

**Pull request merged**
