### PR TITLE
MCHECKSTYLE-374 remove deprecated method calls

### PR DESCRIPTION
**Pull request by rnveach**
Since maven-checkstyle upgrade it's default version of checkstyle, we are hoping that we can replace the use of deprecated methods. This replaces deprecated methods with their newer replacements.
These methods have been deprecated since probably 8.2 but can't be removed from main repo because the plugin still uses them and this would break our own CI which relies on the plugin. This would break backward compatibility in the plugin as these only came around at 8.2.

`ConfigurationLoader.loadConfiguration` is also deprecated but hasn't been converted yet because I wanted your input on how you wanted to convert `request.isOmitIgnoredModules()` to the enumeration `IgnoredModulesOptions` as there is no conversion method.

> MCHECKSTYLE-XXX

Let me know if you are willing to accept this and it needs a JIRA.

> mvn -Prun-its clean verify

This doesn't pass for me even on master.
````
[INFO] --- maven-invoker-plugin:3.1.0:integration-test (integration-test) @ maven-checkstyle-plugin ---
[INFO] Building: check-fail\pom.xml
[INFO] run post-build script verify.groovy
[INFO]           check-fail\pom.xml ............................... FAILED (0.5 s)
[INFO]   The post-build script did not succeed. assert buildLog.text.contains( "You have 1 Checkstyle violation" )
       |        |    |
       |        |    false
       |        Running post-build script: D:\Rickys\Java\checkstyleWorkspaceEclipse\maven-checkstyle-plugin\target\it\check-fail\verify.groovy
       D:\Rickys\Java\checkstyleWorkspaceEclipse\maven-checkstyle-plugin\target\it\check-fail\build.log
````

---------------------------------------------

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MCHECKSTYLE) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MCHECKSTYLE-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MCHECKSTYLE-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by rnveach** [comment]
Hmm somehow I was under the impression https://github.com/apache/maven-checkstyle-plugin/pull/13 had already been merged. Sorry for jumping the gun.

**Comment by eolivelli** [comment]
Yes, the upgrade of checkstyle has been merged

**Comment by eolivelli** [comment]
I am investigating the failures on Travis.
meanwhile can you @rnveach please create a JIRA and follow the guidelines?
Having the JIRA will help us taking care of release notes and bug tracking/new features

**Comment by rnveach** [comment]
> please create a JIRA and follow the guidelines?

Done. I will fix the commit message shortly.
https://issues.apache.org/jira/browse/MCHECKSTYLE-374

**Comment by rnveach** [comment]
Commit message was updated.
> ConfigurationLoader.loadConfiguration is also deprecated but hasn't been converted yet 

This was done too.

**Comment by rnveach** [comment]
@eolivelli 
> I am investigating the failures on Travis.

As stated above, this methods were just introduced into 8.2 so anything before that will not work as this is a breaking compatibility change.
These tests force usage of an old checkstyle version.

https://github.com/apache/maven-checkstyle-plugin/blob/master/src/it/MCHECKSTYLE-332_cache-treewalker/pom.xml#L46
https://github.com/apache/maven-checkstyle-plugin/blob/master/src/it/MCHECKSTYLE-332_cache-checker/pom.xml#L46

The one for the cache in checker can use the newer version. The one in treewalker will have to be removed as there will be no version that supports it.
Are you ok with these changes?

**Comment by romani** [comment]
@eolivelli, please review proposal of removal of old tests from @rnveach .

after this update plugin will not be compatible with checkstyle version less than 8.2. 
Here is commit https://github.com/checkstyle/checkstyle/commit/dc88a9954baf88df6543cf73baabed710f882363

This update is very desirable by checkstyle project, as maven plugin is the only reason why we keep this methods as deprecated for long time. This update would allow us to move  further in API cleanup.
It would very helpful for checkstyle project to have such fix in next release.

@rnveach, lets propose you update as second commit. Please also put ticks on all items in description.

**Comment by eolivelli** [comment]
Okay, let's drop the test which is not compatible with new checkstyle API.

You can do it in this commit


Thank you all guys, I hope we will hve soon a great brand new release of this plugin

**Comment by rnveach** [comment]
@eolivelli done but it looks like travis is facing the same issue our repo is having, downloading open jdk 9+.

I also made some additional changes to `DefaultCheckstyleExecutor` and removed the outdated form of setting the cache since the old ITs that supported it are gone.

**Comment by rnveach** [comment]
> > mvn -Prun-its clean verify

> This doesn't pass for me even on master.

I figured out my problem. It won't work with Eclipse's embedded maven and needs a real maven installation. I ran all the tests and they pass.

**Comment by eolivelli** [comment]
Tests passed on Apache CI
https://builds.apache.org/job/maven-box/job/maven-checkstyle-plugin/job/MCHECKSTYLE-374/

**Pull request closed without merging**
