### PR TITLE
[MCHECKSTYLE-365] Correct counts in Rules section

### PR DESCRIPTION
**Pull request by rturner-edjuster**
When the site report is generated, in the Rules section, the plug-in
groups together the violation counts for rules that have the same name
and message, but that have different severity levels – specifically
where one of the rules doesn't specify a severity level and uses the
default (error). This results in both rules being listed with different
properties and severity levels, but with the same violation count (which
is incorrect).

This change allows the rule matching to fall through to the most
specific match rather than short-circuiting the match on success. This
corrects the case where two rules of the same name have the same message
but different severities and allows the match to proceed to check
further conditions, such as the severity.

In addition, this change also ensures that the severity is retrieved in
the same way (by providing a default of "error" when missing) as the
logic that displays the rule rows in the Rules section.

Both of these changes are required to properly correct the issue.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MCHECKSTYLE) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MCHECKSTYLE-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MCHECKSTYLE-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 -  In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by rturner-edjuster** [comment]
(Nudge, in case this has been forgotten).

**Comment by eolivelli** [comment]
Here it is the CI job
https://builds.apache.org/job/maven-box/job/maven-checkstyle-plugin/job/MCHECKSTYLE-365/

**Comment by rturner-edjuster** [comment]
Just wondering if there are steps you want me to take with the build (sorry, not committed to this project before). Let me know if you want me to do anything with it.

**Comment by eolivelli** [comment]
No. 
CI tests passed the patch is good to go.
I will merge tomorrow (don't have my laptop at the moment)

Thank you very much

**Comment by rturner-edjuster** [comment]
Great stuff. Thanks.

**Comment by eolivelli** [comment]
Committed as eee0ba18a70e6d6bd51797c70a83cf844f882286
thank you !

**Comment by jira-importer** [comment]
Resolve #277

**Pull request closed without merging**
