### PR TITLE
[MCHECKSTYLE-375] - update all xml doctypes to latest

### PR DESCRIPTION
**Pull request by rnveach**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MCHECKSTYLE) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MCHECKSTYLE-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MCHECKSTYLE-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [X] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by eolivelli** [comment]
waiting for CI https://builds.apache.org/job/maven-box/job/maven-checkstyle-plugin/job/MCHECKSTYLE-375/

**Comment by eolivelli** [comment]
committed as 850f7cc398171b089500e84c20ec1cedefbdb311

**Comment by eolivelli** [comment]
@rnveach @romani can you please take a look to https://issues.apache.org/jira/browse/MCHECKSTYLE-376 ?

Please subscribe to dev@maven mailing list so that we can follow up with discussion about this plugin inside Maven community

**Comment by romani** [comment]
@rnveach, I need your help to check this issue
https://issues.apache.org/jira/browse/MCHECKSTYLE-376 it is windows specific. I left investigation notes.

**Comment by romani** [comment]
>Please subscribe to dev@maven mailing list so that we can follow up with discussion about this plugin inside Maven community

https://lists.apache.org/list.html?dev@maven.apache.org is too active group to subscribe and follow. I have 2k of message in our project in my to-do list for review and response. Extra subsciption will blow my mailbox. But I completely ok to be pinned (even few times) in GitHub. I can reply to some post or you can get it from our library maillist , so you will know my email, so you can CC me when required.

**Comment by eolivelli** [comment]
@romani I see.
Thank you for all of your support.
I am very glad to collaborate with checkstyle community

**Comment by jira-importer** [comment]
Resolve #287

**Pull request closed without merging**
