### PR TITLE
[MCHECKSTYLE-388] Update internal dependencies with low impact

### PR DESCRIPTION
**Pull request by hazendaz**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MCHECKSTYLE) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MCHECKSTYLE-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MCHECKSTYLE-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by eolivelli** [comment]
waiting for https://builds.apache.org/job/maven-box/job/maven-checkstyle-plugin/job/MCHECKSTYLE-388/

**Comment by hazendaz** [comment]
@eolivelli Question for you.  I've never seen a rebase seemingly appear to no longer have commits.  Is this because you possibly merged elsewhere and this is simply a mirror?  Obviously the PR was still open thus it shows me closing it as a result of syncing up the merged performed to master.  And as a result, shows no changes even though they are clearly there ;)

**Comment by eolivelli** [comment]
@hazendaz

I have squashed all of the commits into one.
Do you think I lost some of them?
Can you please double check?

I apologize for this inconvenience

**Comment by hazendaz** [comment]
@eolivelli No inconvenience.  Everything is there.  I always double check before pushing back up to my remote fork when a squash has occurred.  What threw me off here was that the PR was still open when I rebased.  So I suspected this was done outside of github and a squash outside of github would result in the commits not matching the PR so it won't auto show as merged.  My subsequent rebase and push then resulted in it auto closing as well as showing no commits on it at all.  So its just the optics of the original PR.  Otherwise all good.  At best anyways all I could have done was close the PR itself anyways.  And I probably would never had known if it were not for jira sending a notice that the PR was changed.

**Comment by eolivelli** [comment]
Yes I did it offline.
We aren't using github api or the 'merge button'

**Comment by jira-importer** [comment]
Resolve #300

**Pull request closed without merging**
